"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from os import popen
from setuptools import setup

APP = ['battery_app.py']
if popen("defaults read -g AppleInterfaceStyle").readline() == "Dark\n":
    icon = 'Assets/Dark/icon.icns'
    DATA_FILES = ["Assets/Dark/battery_charging_icon.png", "Assets/Dark/battery_charging_1.png",
                  "Assets/Dark/battery_charging_2.png", "Assets/Dark/battery_charging_3.png",
                  "Assets/Dark/battery_charging_4.png", "Assets/Dark/battery_charging_5.png"]
else:
    icon = 'Assets/Light/icon.icns'
    DATA_FILES = ["Assets/Light/battery_charging_icon.png", "Assets/Light/battery_charging_1.png",
                  "Assets/Light/battery_charging_2.png", "Assets/Light/battery_charging_3.png",
                  "Assets/Light/battery_charging_4.png", "Assets/Light/battery_charging_5.png"]

DATA_FILES.append("send_battery_notification.scpt")
OPTIONS = {
    'argv_emulation': True,
    'iconfile': icon,
    'plist': {
        'LSUIElement': True
    }
}

setup(
    app=APP,
    name="Battery App",
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
